language: java
jdk: oraclejdk8
os: linux
dist: trusty

cache:
  directories:
    - $HOME/.m2
before_cache:
  # ensure that we do not keep bonitasoft artifacts accross builds
  - rm -f $HOME/.m2/repository/org/bonitasoft

addons:
  sonarcloud:
    organization: "freakey17-github"
    token: $SONAR_TOKEN7

script: - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
./mvnw --show-version --errors test


branches:
  only:
    - master
    - dev
